- hosts: localhost
  vars:
    source_key: "{{ playbook_dir }}/ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    projects: "{{ lookup('env', 'HOME') }}/repos"
  pre_tasks:
    - name: Update dnf
      become: true
      dnf:
        update_cache: true
        state: latest
      tags:
        - install
        - core
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/tlp.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/projects.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/php.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/apps.yml
    - include_tasks: tasks/flatpak.yml
    - include_tasks: tasks/flatpak_apps.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/gnome.yml
    - include_tasks: tasks/kbd_layout.yml
    - include_tasks: tasks/kbd_shortcuts.yml
