- name: Download Chrome RPM package
  get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
    dest: "/tmp/Chrome.rpm"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"

- name: Install Chrome
  become: true
  validate_certs: no
  dnf:
    name: "/tmp/Chrome.rpm"
    state: present

- name: Download Slack RPM package
  get_url:
    url: "https://downloads.slack-edge.com/releases/linux/4.32.122/prod/x64/slack-4.32.122-0.1.el8.x86_64.rpm"
    dest: "/tmp/Slack.rpm"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Slack/93.0.4577.63 Safari/537.36"

- name: Install Slack
  become: true
  validate_certs: no
  dnf:
    name: "/tmp/Slack.rpm"
    state: present

- name: Download Code
  get_url:
    url: "https://az764295.vo.msecnd.net/stable/b3e4e68a0bc097f0ae7907b217c1119af9e03435/code-1.78.2-1683731087.el7.x86_64.rpm"
    dest: "/tmp/Code.rpm"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/93.0.4577.63 Safari/537.36"

- name: Install Code
  become: true
  validate_certs: no
  dnf:
    name: "/tmp/Code.rpm"
    state: present

- name: Download Upwork RPM package
  get_url:
    url: "https://upwork-usw2-desktopapp.upwork.com/binaries/v5_8_0_24_aef0dc8c37cf46a8/upwork-5.8.0.24-1fc24.x86_64.rpm"
    dest: "/tmp/Upwork.rpm"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"

- name: Install Upwork
  become: true
  validate_certs: no
  dnf:
    name: "/tmp/Upwork.rpm"
    state: present

- name: Download Docker RPM package
  get_url:
    url: "https://desktop.docker.com/linux/main/amd64/docker-desktop-4.19.0-x86_64.rpm?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64"
    dest: "/tmp/Docker.rpm"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"

- name: Install Docker
  become: true
  validate_certs: no
  dnf:
    name: "/tmp/Docker.rpm"
    state: present

- name: Clean up temporary file
  become: true
  file:
    path: "/tmp"
    state: absent
