- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

- name: Install Node.js
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 16"
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/bash
