- name: Install TLP
  become: true
  dnf:
    name:
      - tlp
    state: present
  tags:
    - install
    - tlp
- name: Enable and start TLP service
  become: true
  systemd:
    name: tlp
    state: started
    enabled: yes
