- name: Install TLP
  become: true
  dnf:
    name:
      - tlp
    state: present
  tags:
    - install
    - tlp
# - name: Start and enable TLP
#   become: true
#   service:
#     name: tlp
#     state: started
#     enabled: yes
#   tags:
#     - install
#     - tlp
